on:
  push:
    branches:
      - main

jobs:
  build:
    container:
      image: amedeedaboville/rust-wasm
      env:
        RUST_VERSION: "nightly"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          cargo build
          cd glsl2hlsl-wasm
          wasm-pack build
          cd www
          npm run build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: website
          path: ./
          
